'use client';

import React from 'react';
import { LawyerBrief as LawyerBriefType, UserContext } from '@/types';
import { Printer, FileText, AlertCircle, HelpCircle, CheckSquare, Shield } from 'lucide-react';

interface LawyerBriefProps {
  brief: LawyerBriefType;
  context?: UserContext;
  documentType?: string;
  isEscalated?: boolean;
}

export function LawyerBrief({ brief, context, documentType, isEscalated }: LawyerBriefProps) {
  const handlePrint = () => {
    if (typeof window !== 'undefined') {
      window.print();
    }
  };

  return (
    <div className="space-y-6">
      {/* Action Header */}
      <div className="flex items-center justify-between gap-4 bg-slate-900 border border-slate-800 p-4 rounded-xl print:hidden">
        <div>
          <h2 className="text-sm font-bold text-amber-400 uppercase tracking-wider flex items-center gap-2">
            <FileText className="w-4 h-4" />
            1-Page Lawyer Brief
          </h2>
          <p className="text-xs text-slate-400 mt-0.5">
            Take this summary to a legal aid professional, advocate, or legal clinic.
          </p>
        </div>
        <button
          type="button"
          onClick={handlePrint}
          className="px-4 py-2 bg-amber-500 hover:bg-amber-400 text-slate-950 font-bold rounded-lg text-xs flex items-center gap-2 transition-colors shadow-md"
        >
          <Printer className="w-4 h-4" />
          Print Brief
        </button>
      </div>

      {/* Printable Container */}
      <article className="bg-slate-900 print:bg-white print:text-black border border-slate-800 print:border-none p-6 sm:p-8 rounded-xl shadow-xl space-y-6 text-xs leading-relaxed">
        {/* Header Title */}
        <header className="border-b border-slate-800 print:border-black/20 pb-4 space-y-2">
          <div className="flex items-center justify-between">
            <h1 className="text-lg font-extrabold text-white print:text-black tracking-tight">
              Aequitas — Client Legal Brief
            </h1>
            <span className="text-[10px] font-mono uppercase px-2 py-0.5 rounded bg-amber-500/10 print:bg-slate-200 text-amber-300 print:text-slate-800 border border-amber-500/30 print:border-slate-400">
              {documentType ? `${documentType.toUpperCase()} CONTRACT` : 'LEGAL DOCUMENT'}
            </span>
          </div>

          <div className="flex flex-wrap items-center gap-4 text-[11px] text-slate-400 print:text-slate-700 font-mono">
            {context?.persona && <span>Persona: <strong>{context.persona}</strong></span>}
            {context?.jurisdiction && <span>Jurisdiction: <strong>{context.jurisdiction}</strong></span>}
            <span>Generated: <strong>{new Date().toLocaleDateString()}</strong></span>
            {isEscalated && (
              <span className="text-rose-400 print:text-rose-700 font-bold uppercase">
                [URGENT LEGAL AID ESCALATION DETECTED]
              </span>
            )}
          </div>
        </header>

        {/* Disclaimer Warning */}
        <div className="bg-amber-500/10 print:bg-amber-50 border border-amber-500/20 print:border-amber-300 p-3 rounded-lg text-amber-200 print:text-amber-900 text-[11px] flex items-start gap-2">
          <Shield className="w-4 h-4 text-amber-400 print:text-amber-700 shrink-0 mt-0.5" />
          <p>
            <strong>Notice to Legal Practitioner:</strong> This brief was generated by Aequitas AI to assist the client in framing key issues. It is informational and does not constitute formal legal advice.
          </p>
        </div>

        {/* Executive Summary */}
        <section className="space-y-2">
          <h3 className="text-xs font-bold text-amber-400 print:text-slate-900 uppercase tracking-wider flex items-center gap-1.5">
            <FileText className="w-3.5 h-3.5" />
            1. Executive Summary
          </h3>
          <p className="text-slate-200 print:text-slate-800 leading-relaxed font-serif bg-slate-950/50 print:bg-slate-100 p-3 rounded-lg border border-slate-800/60 print:border-slate-300">
            {brief.summary}
          </p>
        </section>

        {/* Key Concerns */}
        <section className="space-y-2">
          <h3 className="text-xs font-bold text-rose-400 print:text-slate-900 uppercase tracking-wider flex items-center gap-1.5">
            <AlertCircle className="w-3.5 h-3.5" />
            2. Key Risk Concerns Identified
          </h3>
          <ul className="space-y-1.5 list-disc list-inside text-slate-300 print:text-slate-800 pl-1">
            {brief.keyConcerns.map((concern, idx) => (
              <li key={idx} className="leading-normal">
                {concern}
              </li>
            ))}
          </ul>
        </section>

        {/* Questions for Advocate */}
        <section className="space-y-2">
          <h3 className="text-xs font-bold text-emerald-400 print:text-slate-900 uppercase tracking-wider flex items-center gap-1.5">
            <HelpCircle className="w-3.5 h-3.5" />
            3. Formulated Questions for Lawyer / Legal Counsel
          </h3>
          <ol className="space-y-1.5 list-decimal list-inside text-slate-300 print:text-slate-800 pl-1">
            {brief.questionsForLawyer.map((q, idx) => (
              <li key={idx} className="leading-normal">
                {q}
              </li>
            ))}
          </ol>
        </section>

        {/* Required Checklist */}
        <section className="space-y-2">
          <h3 className="text-xs font-bold text-sky-400 print:text-slate-900 uppercase tracking-wider flex items-center gap-1.5">
            <CheckSquare className="w-3.5 h-3.5" />
            4. Supporting Documents to Provide Lawyer
          </h3>
          <ul className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-slate-300 print:text-slate-800">
            {brief.documentChecklist.map((docItem, idx) => (
              <li key={idx} className="bg-slate-950/40 print:bg-slate-100 p-2 rounded border border-slate-800 print:border-slate-300 flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-sky-400 print:bg-slate-700 shrink-0" />
                <span>{docItem}</span>
              </li>
            ))}
          </ul>
        </section>

        {/* Legal Aid Referral Footer */}
        <footer className="pt-4 border-t border-slate-800 print:border-slate-400 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-2 text-[10px] text-slate-400 print:text-slate-600">
          <div>
            <strong>Free Legal Aid Helplines (India):</strong> NALSA Helpline: 15100 | Tele-Law: 14416 | National Consumer Helpline: 1915
          </div>
          <div className="font-mono">
            Aequitas Legal Engine v0.1
          </div>
        </footer>
      </article>
    </div>
  );
}
