import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { SynthesisResultSchema, UserContextSchema, LawyerBriefSchema } from '@/lib/schemas';

const BriefRequestSchema = z.object({
  synthesis: SynthesisResultSchema.optional(),
  lawyerBrief: LawyerBriefSchema.optional(),
  context: UserContextSchema.optional(),
  documentType: z.string().optional(),
});

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const parseResult = BriefRequestSchema.safeParse(body);

    if (!parseResult.success) {
      return NextResponse.json(
        { error: 'Invalid brief request payload.', details: parseResult.error.format() },
        { status: 400 }
      );
    }

    const { synthesis, lawyerBrief: providedBrief, context, documentType } = parseResult.data;

    const brief = providedBrief || synthesis?.lawyerBrief;

    if (!brief) {
      return NextResponse.json(
        { error: 'No lawyer brief data provided in payload.' },
        { status: 400 }
      );
    }

    // Format plain-text markdown export version
    const markdownExport = `
# AEQUITAS CLIENT LEGAL BRIEF
**Document Type:** ${documentType || 'Contract'}
**Persona:** ${context?.persona || 'Client'} | **Jurisdiction:** ${context?.jurisdiction || 'India'}
**Date Generated:** ${new Date().toLocaleDateString()}

---

## 1. EXECUTIVE SUMMARY
${brief.summary}

---

## 2. KEY RISK CONCERNS
${brief.keyConcerns.map((c, i) => `${i + 1}. ${c}`).join('\n')}

---

## 3. QUESTIONS FOR ADVOCATE / LEGAL AID
${brief.questionsForLawyer.map((q, i) => `${i + 1}. ${q}`).join('\n')}

---

## 4. SUPPORTING DOCUMENTS TO PROVIDE
${brief.documentChecklist.map((d) => `- ${d}`).join('\n')}

---

*Notice: Generated by Aequitas AI for legal assistance and intake preparation. Not formal legal advice.*
`.trim();

    return NextResponse.json(
      {
        brief,
        context,
        documentType: documentType || 'contract',
        markdownExport,
      },
      { status: 200 }
    );
  } catch (err: any) {
    console.error('[/api/brief] error:', err?.message);
    return NextResponse.json(
      { error: 'Failed to process legal brief.' },
      { status: 500 }
    );
  }
}
